# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "deal-ai"
client_id = "52c88f789e52c89b2061877c6eab2057"
application_url = "https://requiring-ceiling-wifi-selective.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://requiring-ceiling-wifi-selective.trycloudflare.com/auth/callback",
  "https://requiring-ceiling-wifi-selective.trycloudflare.com/auth/shopify/callback",
  "https://requiring-ceiling-wifi-selective.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-de06169f.myshopify.com"
